// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

/**
 * Phase 12 — StudyLab Procedural Anchor Smoke Tests
 *
 * Verifies the real runtime path:
 *   APKG import → Anki collection → renderExistingCard → ProceduralReviewer HTML
 *
 * The fixture (Procedural_StudyLab_Fixture.apkg) is generated by
 * generate_procedural_apkg.py and must exist at the repo root before
 * these tests run.
 *
 * Launch environment: qt/tests/launch_anki_for_e2e.py (isolated temp profile,
 * offscreen Qt, mediasrv on ANKI_API_PORT / 40000).
 *
 * Schema IDs match catalog.rs constants exactly:
 *   SCHEMA_SUCCESSIVE_PERCENTAGE = "successive_percentage"    (Math)
 *   SCHEMA_REASONING_SEATING     = "reasoning_seating_linear" (Reasoning)
 */

import * as path from "path";
import * as url from "url";

import {
    RenderCardResponse,
    RenderExistingCardRequest,
} from "@generated/anki/card_rendering_pb";
import {
    ImportAnkiPackageOptions,
    ImportAnkiPackageRequest,
    ImportResponse,
} from "@generated/anki/import_export_pb";
import { SearchRequest, SearchResponse } from "@generated/anki/search_pb";
import { expect, test } from "@playwright/test";

import { callRpc } from "./helpers";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
// Repo root: ts/tests/e2e → ../../../
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..", "..", "..");
const FIXTURE_PATH = path.join(REPO_ROOT, "Procedural_StudyLab_Fixture.apkg");

async function importFixture(page): Promise<void> {
    const resp = ImportResponse.fromBinary(
        await callRpc(
            page,
            "importAnkiPackage",
            new ImportAnkiPackageRequest({
                packagePath: FIXTURE_PATH,
                options: new ImportAnkiPackageOptions({
                    mergeNotetypes: true,
                }),
            }),
        ),
    );
    // Non-empty log means Anki processed the package (even if some notes
    // were already present from a previous run).
    expect(resp).toBeDefined();
}

async function findCardsByTag(page, tag: string): Promise<bigint[]> {
    const resp = SearchResponse.fromBinary(
        await callRpc(
            page,
            "searchCards",
            new SearchRequest({ search: `tag:${tag}` }),
        ),
    );
    return resp.ids;
}

async function renderCard(page, cardId: bigint): Promise<RenderCardResponse> {
    return RenderCardResponse.fromBinary(
        await callRpc(
            page,
            "renderExistingCard",
            new RenderExistingCardRequest({
                cardId,
                browser: false,
                partialRender: false,
            }),
        ),
    );
}

/** Extract joined text from all RenderedTemplateNode text nodes. */
function extractHtml(rendered: RenderCardResponse): string {
    const parts: string[] = [];
    for (const node of rendered.questionNodes) {
        if (node.value && typeof node.value === "object" && "text" in node.value) {
            parts.push(String((node.value as any).text));
        }
    }
    return parts.join("");
}

// ---------------------------------------------------------------------------
// Shared page fixture (no editor needed — these are reviewer-path tests)
// ---------------------------------------------------------------------------

let _imported = false;

test.beforeAll(async ({ browser }) => {
    // Import the fixture once for the entire suite.
    const page = await browser.newPage();
    try {
        await page.goto("/congrats", { waitUntil: "domcontentloaded" });
        if (!_imported) {
            await importFixture(page);
            _imported = true;
        }
    } finally {
        await page.close();
    }
});

// ---------------------------------------------------------------------------
// Test 1: APKG import
// ---------------------------------------------------------------------------

test("procedural fixture: APKG imports successfully", async ({ page }) => {
    await page.goto("/congrats", { waitUntil: "domcontentloaded" });
    // Re-import is idempotent — verifies the import RPC itself responds OK.
    await importFixture(page);
    const cards = await findCardsByTag(page, "StudyLab_Math_Fixture");
    expect(cards.length).toBeGreaterThanOrEqual(1);
});

// ---------------------------------------------------------------------------
// Test 2: Math card renders ProceduralReviewer HTML
// ---------------------------------------------------------------------------

test("procedural fixture: math card renders ProceduralReviewer HTML", async ({
    page,
}) => {
    await page.goto("/congrats", { waitUntil: "domcontentloaded" });

    const cards = await findCardsByTag(page, "StudyLab_Math_Fixture");
    expect(cards.length).toBeGreaterThanOrEqual(1);

    const rendered = await renderCard(page, cards[0]);
    const html = extractHtml(rendered);

    // render.rs:248 — render_procedural_anchor() produces ReviewerHTML from template.rs
    expect(html).toContain('id="procedural-card"');
    expect(html).toContain('id="proc-stopwatch"');
    expect(html).toContain('id="proc-submit-btn"');
    expect(html).toContain('id="proc-result-panel"');

    // ProceduralReviewer init hook must be present in the script block
    expect(html).toContain("window.anki.procedural.setup");

    // Schema must be successive_percentage (Mathematics domain)
    expect(html).toContain("successive_percentage");

    // Must NOT contain raw error fallback — engine must have generated the problem
    expect(html).not.toContain("Procedural Engine Error");
    expect(html).not.toContain("ProceduralPayload field is missing");
});

// ---------------------------------------------------------------------------
// Test 3: Incorrect answer smoke — mistake classification UI
// ---------------------------------------------------------------------------

test("procedural fixture: incorrect-answer card contains mistake classification options", async ({
    page,
}) => {
    await page.goto("/congrats", { waitUntil: "domcontentloaded" });

    // Use the seed-99 card (second math card, tagged Incorrect)
    const cards = await findCardsByTag(page, "StudyLab_Math_Fixture_Incorrect");
    expect(cards.length).toBeGreaterThanOrEqual(1);

    const rendered = await renderCard(page, cards[0]);
    const html = extractHtml(rendered);

    // Must be a valid procedural card
    expect(html).toContain('id="procedural-card"');
    expect(html).not.toContain("Procedural Engine Error");

    // The mistake classification UI is built by ProceduralReviewer.ts in the
    // browser on incorrect submission — it is not in the static server HTML.
    // We confirm the ProceduralReviewer initialization script is present so
    // the browser can construct it at runtime.
    expect(html).toContain("window.anki.procedural.setup");

    // correctAnswer must be serialised into the script options block so the
    // browser can compare the submitted answer and show the mistake buttons.
    expect(html).toContain("correctAnswer");
});

// ---------------------------------------------------------------------------
// Test 4: Reasoning card — different schema, different domain
// ---------------------------------------------------------------------------

test("procedural fixture: reasoning card renders with reasoning schema", async ({
    page,
}) => {
    await page.goto("/congrats", { waitUntil: "domcontentloaded" });

    const cards = await findCardsByTag(page, "StudyLab_Reasoning_Fixture");
    expect(cards.length).toBeGreaterThanOrEqual(1);

    const rendered = await renderCard(page, cards[0]);
    const html = extractHtml(rendered);

    // Must be a valid procedural card
    expect(html).toContain('id="procedural-card"');
    expect(html).not.toContain("Procedural Engine Error");

    // Schema must be the reasoning one, not the math one
    expect(html).toContain("reasoning_seating_linear");
    expect(html).not.toContain("successive_percentage");

    // ProceduralReviewer init present
    expect(html).toContain("window.anki.procedural.setup");

    // familyId attribute must differ from the math card family
    expect(html).not.toContain("family.math.percentage");
});
